### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by KatieMFritz** [sindresorhus/gulp-nunjucks#22]
Hello! I'm trying to use `gulp-nunjucks` to compile Twig syntax in [PatternLab Node Gulp edition](https://github.com/pattern-lab/edition-node-gulp).

I keep getting the following error, and I'm not sure how to resolve it:
```
TypeError in plugin 'gulp-nunjucks'
Message: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
Details:
    fileName: // first .twig file in my gulp.src
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
 Here's the relevant part of my `gulpfile.js`:
```.js
const nunjucks_gulp = require('gulp-nunjucks');
const nunjucks_lib = require('nunjucks');

gulp.task('nunjucks', () =>
  gulp.src(normalizePath(paths().source.templates + '**/*.twig'))
   .pipe(nunjucks_gulp.compile(
      {},
      {env: new nunjucks_lib.Environment(new nunjucks_lib.FileSystemLoader(normalizePath(paths().source.patterns)))}
    ))
    .pipe(gulp.dest(normalizePath(paths().public.templates)))
);
```

I understand that `compile` takes two arguments, `data` and `options`. It seems like I have two arguments there, `{}` and my `env` option. 

My end goal is to get html files in my `public.templates` directory, so maybe there is a function I could use besides `compile`? I'm open. If I replace `compile` with `precompile` and remove the first argument, `gulp nunjucks` completes with no errors, but it doesn't seem like it actually does anything. 

Please help me figure out what I'm missing! Thank you in advance. 🙇‍♀️
